name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      
      - uses: jonabc/setup-licensed@v1
        with:
          version: '2.x' # required: supports matching based on string equivalence or node-semver range
          install-dir: /path/to/install/at # optional: defaults to /usr/local/bin
          github_token: "${{ secrets.PERSONAL_TOKEN }}"
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
            
      - name: Installing dependencies
        run: npm install
        
      - name: Deploy
        run: npm run deploy
